name: Release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Setup Build Environment
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild /p:Configuration=Release SharedStopEnabler.sln

      - name: Get Version Number
        id: get_version_number
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Pack Assets
        id: pack_assets
        run: |
          $ErrorView = 'NormalView'
          $env:ASSET_FILE_PATH = "bin/Release/SharedStopEnabler.${{ steps.get_version_number.outputs.VERSION }}.zip"
          $env:ASSET_FILE_NAME = "SharedStopEnabler.${{ steps.get_version_number.outputs.VERSION }}.zip"
          Compress-Archive -Path bin/Release/*.dll -DestinationPath $env:ASSET_FILE_PATH -CompressionLevel Optimal
          echo "::set-output name=ASSET_FILE::$env:ASSET_FILE_PATH"
          echo "::set-output name=ASSET_FILE_NAME::$env:ASSET_FILE_NAME"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version_number.outputs.VERSION }}
          body: |
            Changes in this Release
            - see [Changelog](https://github.com/CodeBardian/SharedStopEnabler/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:          
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.pack_assets.outputs.ASSET_FILE_PATH }}
          asset_name: ${{ steps.pack_assets.outputs.ASSET_FILE_NAME }}
          asset_content_type: application/zip
